name: 'setup jdk8 and sbt cache'
description: 'Checkout Repo / Setup JDK 8 / sbt-cache by SO'

inputs:
  token:
    required: true
    description: 'token to checkout repo'
  fetch-depth:
    required: false
    description: 'fetch-depth to checkout repo'
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}

    - name: Setup JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: SBT Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
          ~/.cache/coursier
        key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
