name: 'setup jdk8 and sbt cache'
description: 'Checkout Repo / Setup JDK 8 / sbt-cache by SO'

runs:
  using: "composite"
  steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: SBT Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
          ~/.cache/coursier
        key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
